
[general]
import = ["~/.config/alacritty/themes/ayu-dark.toml"]
live_config_reload = true

[window]
padding = { x = 20, y = 20 }
dynamic_padding = true
blur = true

[font]
size = 16 
normal = { family = "JetBrainsMono Nerd Font"}

[cursor]
style = { shape = "block", blinking = "Never" }
thickness = 0.15

[terminal]
osc52 = "CopyPaste"
